"""Static campaign catalog mirroring supabase/seed.sql (offline + tests).

SOURCE OF TRUTH: ``supabase/seed.sql``. Keep this module in sync when seed changes
(templates, package ids, prebuilt sheets, ability codes).
"""

from __future__ import annotations

from typing import Any

RULESET_ID = "a0000001-0000-4000-8000-000000000001"

ABILITY_ID_MAP: dict[str, str] = {
    "WAR-S1": "weapon_focus",
    "WAR-S2": "tough",
    "WAR-S3": "armored_defense",
    "WAR-S4": "power_strike",
    "RAN-S1": "marksman",
    "RAN-S2": "keen_senses",
    "RAN-S3": "lightfoot",
    "RAN-S4": "favored_terrain",
    "MAG-S1": "arcane_affinity",
    "MAG-S2": "expanded_mana",
    "MAG-S3": "cantrip_mastery",
    "MAG-S4": "scholar",
    "BRD-S1": "silver_tongue",
    "BRD-S2": "inspiring_presence",
    "BRD-S3": "jack_of_all_trades",
    "BRD-S4": "musical_focus",
}

TEMPLATES: list[dict[str, Any]] = [
    {
        "id": "a0000003-0000-4000-8000-000000000001",
        "slug": "fantasy-lost-mine",
        "name": "Lost Mine of Phandelver",
        "description": (
            "Take up a seemingly harmless delivery job for Gundren, when things "
            "almost immediately go sideways, pulling the adventurers into a "
            "tangled web of treasure hunting, betrayal, and danger."
        ),
        "genre": "fantasy",
        "level_min": 1,
        "level_max": 5,
        "estimated_sessions": "4–6",
        "content_path": "LostMineOfPhandelverAdapted",
        "cover_image_url": None,
        "ruleset_id": RULESET_ID,
        "recommended_players": 4,
        "avg_level": 3,
        "time_max": 50,
        "opening_scene": "Road to Phandalin",
        "opening_chapter": 1,
        "opening_time_current": 50,
    },
    {
        "id": "a0000003-0000-4000-8000-000000000002",
        "slug": "fantasy-touch-of-the-necromancer",
        "name": "Touch of the Necromancer",
        "description": (
            "Someone you care about is fading under a dark curse. Hunt what you "
            "need before the last hour burns out — if you dare."
        ),
        "genre": "fantasy",
        "level_min": 1,
        "level_max": 3,
        "estimated_sessions": "2–3",
        "content_path": "TouchOfTheNecromancerAdapted",
        "cover_image_url": None,
        "ruleset_id": RULESET_ID,
        "recommended_players": 1,
        "avg_level": 2,
        "time_max": 35,
        "opening_scene": "Abandoned roadside shrine",
        "opening_chapter": 1,
        "opening_time_current": 35,
    },
]

# package_id -> package row
PACKAGES: dict[str, dict[str, Any]] = {}

PREBUILTS: list[dict[str, Any]] = []


def _pkg(
    pid: str,
    template_id: str,
    class_id: str,
    label: str,
    theme: str,
    playstyle: str,
    ability_id: str,
    package_data: dict[str, Any],
    sort_order: int,
) -> None:
    PACKAGES[pid] = {
        "id": pid,
        "campaign_template_id": template_id,
        "class_id": class_id,
        "label": label,
        "theme": theme,
        "playstyle": playstyle,
        "ability_id": ability_id,
        "package_data": package_data,
        "sort_order": sort_order,
    }


def _pre(
    pid: str,
    template_id: str,
    class_id: str,
    name_male: str,
    name_female: str,
    race_id: str,
    package_id: str,
    ability_id: str,
    character_data: dict[str, Any],
    hook: str,
    sort_order: int,
) -> None:
    PREBUILTS.append(
        {
            "id": pid,
            "campaign_template_id": template_id,
            "class_id": class_id,
            "name_male": name_male,
            "name_female": name_female,
            "level": 1,
            "race_id": race_id,
            "default_package_id": package_id,
            "starting_ability_id": ability_id,
            "character_data": character_data,
            "hook": hook,
            "sort_order": sort_order,
        }
    )


LM = "a0000003-0000-4000-8000-000000000001"
TN = "a0000003-0000-4000-8000-000000000002"

# --- Lost Mine packages ---
_pkg(
    "lm-warrior-wagon-guard",
    LM,
    "warrior",
    "Wagon Guard",
    "Hired steel for Gundren's supply wagon",
    "Shield wall / durable melee",
    "WAR-S3",
    {
        "equipped_weapon": "Longsword",
        "equipped_armor": "Chain Mail",
        "inventory": [
            "Longsword",
            "Shield",
            "Handaxe",
            "Rope",
            "Crowbar",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": [],
        "armor_evasion_bonus": 3,
        "shield_evasion_bonus": 1,
    },
    1,
)
_pkg(
    "lm-warrior-goblin-slayer",
    LM,
    "warrior",
    "Goblin Slayer",
    "Triboar Trail killer — smash Cragmaw raiders",
    "Heavy damage, aggressive",
    "WAR-S4",
    {
        "equipped_weapon": "Greataxe",
        "equipped_armor": "Scale Mail",
        "inventory": [
            "Greataxe",
            "Javelin x4",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": [],
        "armor_evasion_bonus": 2,
        "shield_evasion_bonus": 0,
    },
    2,
)
_pkg(
    "lm-ranger-trail-sniper",
    LM,
    "ranger",
    "Trail Sniper",
    "Overwatch on the Neverwinter → Phandalin road",
    "Longbow hunter",
    "RAN-S1",
    {
        "equipped_weapon": "Longbow",
        "equipped_armor": "Studded Leather",
        "inventory": [
            "Longbow",
            "Shortsword",
            "Arrows x24",
            "Hunter's Kit",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": [],
        "armor_evasion_bonus": 1,
        "shield_evasion_bonus": 0,
    },
    1,
)
_pkg(
    "lm-ranger-cave-scout",
    LM,
    "ranger",
    "Cave Scout",
    "Cragmaw hideouts and Wave Echo tunnels",
    "Stealth skirmish / traps",
    "RAN-S3",
    {
        "equipped_weapon": "Shortsword",
        "equipped_armor": "Leather",
        "inventory": [
            "Shortsword",
            "Shortbow",
            "Arrows x16",
            "Hunting Trap x2",
            "Chalk",
            "Climbing kit",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": [],
        "armor_evasion_bonus": 1,
        "shield_evasion_bonus": 0,
    },
    2,
)
_pkg(
    "lm-mage-ember-elementalist",
    LM,
    "mage",
    "Ember Elementalist",
    "Fire elementalist — forge-heat and battlefield flame",
    "Elemental damage (fire)",
    "MAG-S1",
    {
        "equipped_weapon": "Ashwood staff",
        "equipped_armor": None,
        "inventory": [
            "Ashwood staff",
            "Spellbook",
            "Charcoal focus",
            "Dagger",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": ["Fire Bolt", "Shocking Grasp", "Light", "Shield"],
        "armor_evasion_bonus": 0,
        "shield_evasion_bonus": 0,
    },
    1,
)
_pkg(
    "lm-mage-glyph-scholar",
    LM,
    "mage",
    "Glyph Scholar",
    "Neverwinter academy — wards, marks, and dungeon lore",
    "Utility / dungeon problem-solving",
    "MAG-S4",
    {
        "equipped_weapon": "Dagger",
        "equipped_armor": None,
        "inventory": [
            "Dagger",
            "Spellbook",
            "Arcane Focus (crystal)",
            "Ink & chalk",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": [
            "Detect Magic",
            "Mage Hand",
            "Arcane Mark",
            "Prestidigitation",
        ],
        "armor_evasion_bonus": 0,
        "shield_evasion_bonus": 0,
    },
    2,
)
_pkg(
    "lm-bard-roadhouse-skald",
    LM,
    "bard",
    "Roadhouse Skald",
    "Songs for caravan camps and Phandalin's Stonehill Inn",
    "Ally buff + light melee",
    "BRD-S2",
    {
        "equipped_weapon": "Rapier",
        "equipped_armor": "Leather",
        "inventory": [
            "Rapier",
            "Lute",
            "Songbook",
            "Dagger",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": ["Healing Word", "Inspire", "Vicious Mockery"],
        "armor_evasion_bonus": 1,
        "shield_evasion_bonus": 0,
    },
    1,
)
_pkg(
    "lm-bard-town-whisper",
    LM,
    "bard",
    "Town Whisper",
    "Soft power in Phandalin — townmasters, Redbrands, rumors",
    "Social intrigue",
    "BRD-S1",
    {
        "equipped_weapon": "Shortsword",
        "equipped_armor": "Studded Leather",
        "inventory": [
            "Shortsword",
            "Flute",
            "Disguise Kit",
            "Calling cards",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": ["Charm", "Disguise Self", "Message"],
        "armor_evasion_bonus": 1,
        "shield_evasion_bonus": 0,
    },
    2,
)

# --- Necromancer packages ---
_pkg(
    "tn-warrior-sisters-shield",
    TN,
    "warrior",
    "Sister's Shield",
    "Protect Sera / hold the line while time burns",
    "Tough frontliner",
    "WAR-S2",
    {
        "equipped_weapon": "Warhammer",
        "equipped_armor": "Chain Mail",
        "inventory": [
            "Warhammer",
            "Shield",
            "Holy water vial",
            "Family locket",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": [],
        "armor_evasion_bonus": 3,
        "shield_evasion_bonus": 1,
    },
    1,
)
_pkg(
    "tn-warrior-gravewarden",
    TN,
    "warrior",
    "Gravewarden",
    "Break bones and shatter undead in the mercury mine",
    "Crushing weapons, undead-focused",
    "WAR-S1",
    {
        "equipped_weapon": "Morningstar",
        "equipped_armor": "Scale Mail",
        "inventory": [
            "Morningstar",
            "Torch x4",
            "Silvered dagger",
            "Crowbar",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
        ],
        "gold": 10,
        "spells_known": [],
        "armor_evasion_bonus": 2,
        "shield_evasion_bonus": 0,
    },
    2,
)
_pkg(
    "tn-ranger-curse-tracker",
    TN,
    "ranger",
    "Curse Tracker",
    "Follow Malachara's trail / find ingredient sources",
    "Tracking + mid-range bow",
    "RAN-S2",
    {
        "equipped_weapon": "Shortbow",
        "equipped_armor": "Studded Leather",
        "inventory": [
            "Shortbow",
            "Shortsword",
            "Arrows x20",
            "Tracking journal",
            "Herbalism Kit",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": [],
        "armor_evasion_bonus": 1,
        "shield_evasion_bonus": 0,
    },
    1,
)
_pkg(
    "tn-ranger-mine-shadow",
    TN,
    "ranger",
    "Mine Shadow",
    "Silent work in abandoned mercury shafts among the undead",
    "Stealth skirmish in darkness",
    "RAN-S3",
    {
        "equipped_weapon": "Shortsword",
        "equipped_armor": "Leather",
        "inventory": [
            "Shortsword",
            "Shortbow",
            "Arrows x15",
            "Dark lantern",
            "Soft boots",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": [],
        "armor_evasion_bonus": 1,
        "shield_evasion_bonus": 0,
    },
    2,
)
_pkg(
    "tn-mage-frost-elementalist",
    TN,
    "mage",
    "Frost Elementalist",
    "Ice elementalist — cold that slows rot and undead",
    "Elemental damage / control (cold)",
    "MAG-S1",
    {
        "equipped_weapon": "Frost-rimed staff",
        "equipped_armor": None,
        "inventory": [
            "Frost-rimed staff",
            "Spellbook",
            "Ice crystal focus",
            "Dagger",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": ["Frost Ray", "Ray of Frost", "Shield", "Mage Hand"],
        "armor_evasion_bonus": 0,
        "shield_evasion_bonus": 0,
    },
    1,
)
_pkg(
    "tn-mage-binding-adept",
    TN,
    "mage",
    "Binding Adept",
    "Grey lore — sense and study necromantic bindings",
    "Detection / utility for the ritual path",
    "MAG-S4",
    {
        "equipped_weapon": "Dagger",
        "equipped_armor": None,
        "inventory": [
            "Dagger",
            "Spellbook",
            "Arcane Focus (bone charm)",
            "Salt pouch",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": [
            "Detect Magic",
            "Light",
            "Prestidigitation",
            "Magic Missile",
        ],
        "armor_evasion_bonus": 0,
        "shield_evasion_bonus": 0,
    },
    2,
)
_pkg(
    "tn-bard-vigil-singer",
    TN,
    "bard",
    "Vigil Singer",
    "Songs to keep Sera's spirit (and the party) going as the clock ticks",
    "Healing / morale support",
    "BRD-S2",
    {
        "equipped_weapon": "Shortsword",
        "equipped_armor": "Leather",
        "inventory": [
            "Shortsword",
            "Lyre",
            "Rest hymns booklet",
            "Healing draught",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": ["Healing Word", "Song of Rest", "Inspire"],
        "armor_evasion_bonus": 1,
        "shield_evasion_bonus": 0,
    },
    1,
)
_pkg(
    "tn-bard-hollowbridge-voice",
    TN,
    "bard",
    "Hollowbridge Voice",
    "Local ties — Evaine, Torval, Vesper, Mara; bargain for ingredients",
    "Social / information",
    "BRD-S1",
    {
        "equipped_weapon": "Rapier",
        "equipped_armor": "Studded Leather",
        "inventory": [
            "Rapier",
            "Mandolin",
            "Letter of introduction",
            "Disguise Kit",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "gold": 10,
        "spells_known": ["Charm", "Friends", "Guidance"],
        "armor_evasion_bonus": 1,
        "shield_evasion_bonus": 0,
    },
    2,
)

# Prebuilts — full character_data (aligned with seed.sql)
_pre(
    "a0000005-0000-4000-8000-000000000001",
    LM,
    "warrior",
    "Aldric of Corlinn Hill",
    "Elara of Corlinn Hill",
    "human",
    "lm-warrior-wagon-guard",
    "WAR-S3",
    {
        "stats": {"might": 2, "finesse": 1, "wit": 0, "presence": -1},
        "hp": 12,
        "hp_max": 12,
        "evasion": 15,
        "mana": None,
        "mana_max": None,
        "xp": 0,
        "gold": 10,
        "conditions": [],
        "class_abilities": ["armored_defense"],
        "spells_known": [],
        "equipped_weapon": "Longsword",
        "equipped_armor": "Chain Mail",
        "inventory": [
            "Longsword",
            "Shield",
            "Handaxe",
            "Rope",
            "Crowbar",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "starting_package_id": "lm-warrior-wagon-guard",
        "ability_id": "WAR-S3",
    },
    "Noble heir seeking to civilize the frontier",
    1,
)
_pre(
    "a0000005-0000-4000-8000-000000000002",
    LM,
    "ranger",
    "Kael Bramblefoot",
    "Mira Bramblefoot",
    "elf",
    "lm-ranger-trail-sniper",
    "RAN-S1",
    {
        "stats": {"might": 0, "finesse": 2, "wit": 1, "presence": -1},
        "hp": 10,
        "hp_max": 10,
        "evasion": 13,
        "mana": None,
        "mana_max": None,
        "xp": 0,
        "gold": 10,
        "conditions": [],
        "class_abilities": ["marksman"],
        "spells_known": [],
        "equipped_weapon": "Longbow",
        "equipped_armor": "Studded Leather",
        "inventory": [
            "Longbow",
            "Shortsword",
            "Arrows x24",
            "Hunter's Kit",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "starting_package_id": "lm-ranger-trail-sniper",
        "ability_id": "RAN-S1",
    },
    "Scout who knows every trail to Phandalin",
    2,
)
_pre(
    "a0000005-0000-4000-8000-000000000003",
    LM,
    "mage",
    "Silas Emberquill",
    "Lyra Emberquill",
    "dragonborn",
    "lm-mage-ember-elementalist",
    "MAG-S1",
    {
        "stats": {"might": -1, "finesse": 0, "wit": 2, "presence": 1},
        "hp": 9,
        "hp_max": 9,
        "evasion": 10,
        "mana": 7,
        "mana_max": 7,
        "xp": 0,
        "gold": 10,
        "conditions": [],
        "class_abilities": ["arcane_affinity"],
        "spells_known": ["Fire Bolt", "Shocking Grasp", "Light", "Shield"],
        "equipped_weapon": "Ashwood staff",
        "equipped_armor": None,
        "inventory": [
            "Ashwood staff",
            "Spellbook",
            "Charcoal focus",
            "Dagger",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "starting_package_id": "lm-mage-ember-elementalist",
        "ability_id": "MAG-S1",
    },
    "Neverwinter apprentice hired for the Rockseeker claim",
    3,
)
_pre(
    "a0000005-0000-4000-8000-000000000004",
    LM,
    "bard",
    "Finn Harpsong",
    "Wren Harpsong",
    "half-orc",
    "lm-bard-roadhouse-skald",
    "BRD-S2",
    {
        "stats": {"might": -1, "finesse": 1, "wit": 0, "presence": 2},
        "hp": 9,
        "hp_max": 9,
        "evasion": 12,
        "mana": 6,
        "mana_max": 6,
        "xp": 0,
        "gold": 10,
        "conditions": [],
        "class_abilities": ["inspiring_presence"],
        "spells_known": ["Healing Word", "Inspire", "Vicious Mockery"],
        "equipped_weapon": "Rapier",
        "equipped_armor": "Leather",
        "inventory": [
            "Rapier",
            "Lute",
            "Songbook",
            "Dagger",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "starting_package_id": "lm-bard-roadhouse-skald",
        "ability_id": "BRD-S2",
    },
    "Road performer with debts waiting in Phandalin",
    4,
)
_pre(
    "a0000005-0000-4000-8000-000000000011",
    TN,
    "warrior",
    "Rowan Ashford",
    "Rena Ashford",
    "human",
    "tn-warrior-sisters-shield",
    "WAR-S2",
    {
        "stats": {"might": 2, "finesse": 1, "wit": 0, "presence": -1},
        "hp": 14,
        "hp_max": 14,
        "evasion": 15,
        "mana": None,
        "mana_max": None,
        "xp": 0,
        "gold": 10,
        "conditions": [],
        "class_abilities": ["tough"],
        "spells_known": [],
        "equipped_weapon": "Warhammer",
        "equipped_armor": "Chain Mail",
        "inventory": [
            "Warhammer",
            "Shield",
            "Holy water vial",
            "Family locket",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "starting_package_id": "tn-warrior-sisters-shield",
        "ability_id": "WAR-S2",
    },
    "Elder sibling desperate to save Sera",
    1,
)
_pre(
    "a0000005-0000-4000-8000-000000000012",
    TN,
    "ranger",
    "Lir Venn",
    "Lira Venn",
    "elf",
    "tn-ranger-curse-tracker",
    "RAN-S2",
    {
        "stats": {"might": 0, "finesse": 2, "wit": 1, "presence": -1},
        "hp": 10,
        "hp_max": 10,
        "evasion": 13,
        "mana": None,
        "mana_max": None,
        "xp": 0,
        "gold": 10,
        "conditions": [],
        "class_abilities": ["keen_senses"],
        "spells_known": [],
        "equipped_weapon": "Shortbow",
        "equipped_armor": "Studded Leather",
        "inventory": [
            "Shortbow",
            "Shortsword",
            "Arrows x20",
            "Tracking journal",
            "Herbalism Kit",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "starting_package_id": "tn-ranger-curse-tracker",
        "ability_id": "RAN-S2",
    },
    "Hollowbridge tracker who senses the curse on the wind",
    2,
)
_pre(
    "a0000005-0000-4000-8000-000000000013",
    TN,
    "mage",
    "Alden Greythorn",
    "Vespera Greythorn",
    "human",
    "tn-mage-frost-elementalist",
    "MAG-S1",
    {
        "stats": {"might": -1, "finesse": 0, "wit": 2, "presence": 1},
        "hp": 9,
        "hp_max": 9,
        "evasion": 10,
        "mana": 7,
        "mana_max": 7,
        "xp": 0,
        "gold": 10,
        "conditions": [],
        "class_abilities": ["arcane_affinity"],
        "spells_known": ["Frost Ray", "Ray of Frost", "Shield", "Mage Hand"],
        "equipped_weapon": "Frost-rimed staff",
        "equipped_armor": None,
        "inventory": [
            "Frost-rimed staff",
            "Spellbook",
            "Ice crystal focus",
            "Dagger",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "starting_package_id": "tn-mage-frost-elementalist",
        "ability_id": "MAG-S1",
    },
    "Hedge mage who studied bindings the temple will not touch",
    3,
)
_pre(
    "a0000005-0000-4000-8000-000000000014",
    TN,
    "bard",
    "Calen Marsh",
    "Callia Marsh",
    "half-orc",
    "tn-bard-vigil-singer",
    "BRD-S2",
    {
        "stats": {"might": -1, "finesse": 1, "wit": 0, "presence": 2},
        "hp": 9,
        "hp_max": 9,
        "evasion": 12,
        "mana": 6,
        "mana_max": 6,
        "xp": 0,
        "gold": 10,
        "conditions": [],
        "class_abilities": ["inspiring_presence"],
        "spells_known": ["Healing Word", "Song of Rest", "Inspire"],
        "equipped_weapon": "Shortsword",
        "equipped_armor": "Leather",
        "inventory": [
            "Shortsword",
            "Lyre",
            "Rest hymns booklet",
            "Healing draught",
            "Explorer's Pack",
            "Waterskin",
            "Bedroll",
            "Rations x3",
            "Torch x2",
        ],
        "starting_package_id": "tn-bard-vigil-singer",
        "ability_id": "BRD-S2",
    },
    "Hollowbridge singer who will not let Sera fade alone",
    4,
)
