#!/bin/bash
# Live Reload Setup Helper Script
# Helps configure Capacitor live reload for mobile development

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔄 Capacitor Live Reload Setup${NC}"
echo ""

# Detect OS
OS="$(uname -s)"
case "${OS}" in
    Linux*)     MACHINE=Linux;;
    Darwin*)    MACHINE=Mac;;
    *)          MACHINE="UNKNOWN:${OS}"
esac

# Get local IP address
echo "Detecting your local IP address..."
if [ "$MACHINE" = "Mac" ]; then
    # macOS
    LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "")
    if [ -z "$LOCAL_IP" ]; then
        # Fallback
        LOCAL_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}')
    fi
elif [ "$MACHINE" = "Linux" ]; then
    # Linux
    LOCAL_IP=$(hostname -I | awk '{print $1}' 2>/dev/null || echo "")
    if [ -z "$LOCAL_IP" ]; then
        # Fallback
        LOCAL_IP=$(ip route get 1.1.1.1 | awk '{print $7; exit}' 2>/dev/null || echo "")
    fi
else
    LOCAL_IP=""
fi

if [ -z "$LOCAL_IP" ]; then
    echo -e "${YELLOW}⚠️  Could not automatically detect IP address${NC}"
    echo "Please enter your machine's IP address:"
    read -r LOCAL_IP
else
    echo -e "${GREEN}✅ Detected IP: ${LOCAL_IP}${NC}"
fi

# Determine platform
echo ""
echo "Which platform are you testing on?"
echo "1) iOS Simulator (use localhost)"
echo "2) Android Emulator (use 10.0.2.2)"
echo "3) Physical Device (use ${LOCAL_IP})"
read -p "Enter choice [1-3]: " PLATFORM_CHOICE

case $PLATFORM_CHOICE in
    1)
        DEV_SERVER_URL="http://localhost:5173"
        CLEARTEXT="false"
        echo -e "${GREEN}✅ Using localhost for iOS Simulator${NC}"
        ;;
    2)
        DEV_SERVER_URL="http://10.0.2.2:5173"
        CLEARTEXT="true"
        echo -e "${GREEN}✅ Using 10.0.2.2 for Android Emulator${NC}"
        ;;
    3)
        DEV_SERVER_URL="http://${LOCAL_IP}:5173"
        CLEARTEXT="true"
        echo -e "${GREEN}✅ Using ${LOCAL_IP} for physical device${NC}"
        ;;
    *)
        echo -e "${RED}❌ Invalid choice${NC}"
        exit 1
        ;;
esac

# Create or update .env.local
ENV_FILE=".env.local"
if [ -f "$ENV_FILE" ]; then
    echo ""
    echo -e "${YELLOW}⚠️  ${ENV_FILE} already exists${NC}"
    read -p "Overwrite? [y/N]: " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        echo "Aborted."
        exit 0
    fi
fi

# Write configuration
cat > "$ENV_FILE" << EOF
# Live Reload Configuration
# Generated by setup-live-reload.sh on $(date)

VITE_CAPACITOR_DEV_SERVER_URL=${DEV_SERVER_URL}
VITE_CAPACITOR_CLEARTEXT=${CLEARTEXT}
EOF

echo ""
echo -e "${GREEN}✅ Configuration written to ${ENV_FILE}${NC}"
echo ""
echo "Next steps:"
echo "1. Rebuild and sync:"
echo "   ${BLUE}npm run build:dev${NC}"
echo "   ${BLUE}npm run cap:sync:dev${NC}"
echo ""
echo "2. Start the dev server:"
echo "   ${BLUE}npm run dev${NC}"
echo ""
echo "3. Run the app on your device - changes will reload automatically!"
echo ""
echo -e "${GREEN}✅ Live reload setup complete!${NC}"
