-- Feature 07: durable player transcript archive (campaign-scoped)

create table if not exists public.playthrough_transcript_entries (
  id uuid primary key default uuid_generate_v4(),
  active_campaign_id uuid not null references public.active_campaigns (id) on delete cascade,
  entry_id text not null,
  entry_order bigint generated by default as identity,
  entry jsonb not null,
  created_at timestamptz not null default now(),
  unique (active_campaign_id, entry_id)
);

create index if not exists idx_pte_campaign_order
  on public.playthrough_transcript_entries (active_campaign_id, entry_order);

create table if not exists public.playthrough_transcript_summaries (
  id uuid primary key default uuid_generate_v4(),
  active_campaign_id uuid not null references public.active_campaigns (id) on delete cascade,
  segment_index integer not null,
  summary_text text not null,
  covered_entry_id_from text,
  covered_entry_id_to text,
  created_at timestamptz not null default now(),
  unique (active_campaign_id, segment_index)
);

create index if not exists idx_pts_campaign_index
  on public.playthrough_transcript_summaries (active_campaign_id, segment_index);

alter table public.playthrough_transcript_entries enable row level security;
alter table public.playthrough_transcript_summaries enable row level security;

drop policy if exists "pte_select_own" on public.playthrough_transcript_entries;
create policy "pte_select_own"
  on public.playthrough_transcript_entries for select to authenticated
  using (
    exists (
      select 1 from public.active_campaigns ac
      where ac.id = playthrough_transcript_entries.active_campaign_id
        and ac.owner_id = public.current_app_user_id()
    )
  );

drop policy if exists "pte_insert_own" on public.playthrough_transcript_entries;
create policy "pte_insert_own"
  on public.playthrough_transcript_entries for insert to authenticated
  with check (
    exists (
      select 1 from public.active_campaigns ac
      where ac.id = playthrough_transcript_entries.active_campaign_id
        and ac.owner_id = public.current_app_user_id()
    )
  );

drop policy if exists "pte_delete_own" on public.playthrough_transcript_entries;
create policy "pte_delete_own"
  on public.playthrough_transcript_entries for delete to authenticated
  using (
    exists (
      select 1 from public.active_campaigns ac
      where ac.id = playthrough_transcript_entries.active_campaign_id
        and ac.owner_id = public.current_app_user_id()
    )
  );

drop policy if exists "pts_select_own" on public.playthrough_transcript_summaries;
create policy "pts_select_own"
  on public.playthrough_transcript_summaries for select to authenticated
  using (
    exists (
      select 1 from public.active_campaigns ac
      where ac.id = playthrough_transcript_summaries.active_campaign_id
        and ac.owner_id = public.current_app_user_id()
    )
  );

drop policy if exists "pts_insert_own" on public.playthrough_transcript_summaries;
create policy "pts_insert_own"
  on public.playthrough_transcript_summaries for insert to authenticated
  with check (
    exists (
      select 1 from public.active_campaigns ac
      where ac.id = playthrough_transcript_summaries.active_campaign_id
        and ac.owner_id = public.current_app_user_id()
    )
  );

grant select, insert, delete on table public.playthrough_transcript_entries to authenticated;
grant select, insert on table public.playthrough_transcript_summaries to authenticated;
grant all on table public.playthrough_transcript_entries to service_role;
grant all on table public.playthrough_transcript_summaries to service_role;
